name: Instrument Request
description: Request a new instrument configuration
title: "[New Instrument]: "
labels: ["new instrument"]
body:
  - type: textarea
    id: instrument-details
    attributes:
      label: Instrument details?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: vendor
    attributes:
      label: Vendor
      description: Vendor Name
  - type: textarea
    id: model
    attributes:
      label: Model
      description: Instrument Name
