name: Instrument Request
description: Request a new instrument configuration
title: "[New Instrument]: "
labels: ["new instrument"]
body:
  - type: input
    id: vendor
    attributes:
      label: Vendor
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Model
    validations:
      required: true
  - type: textarea
    id: instrument-details
    attributes:
      label: Instrument Details
      description: Give a detailed description of the data, including folder structure, variable locations, and naming conventions. Be sure to include where Project, Subject, and Session fields will be pulled from. See https://sydneyuni.atlassian.net/wiki/spaces/RC/pages/960563238/MR+Solutions+3T+7T+MRI as an example
      placeholder: Tell us how your data is structure1
      value: "Description of data hierachy"
    validations:
      required: true
  - type: textarea
    id: institution-details
    attributes:
      label: Affected Nodes
      placeholder: Node, Number of instruments
      value: "Please detail which nodes this affects, including how many instruments are affected per node"
    validations:
      required: true
