name: Instrument Request
description: Request a new instrument configuration
title: "[New Instrument]: "
labels: ["new instrument"]
body:
  - type: input
    id: vendor
    attributes:
      label: Vendor
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Model
    validations:
      required: true
  - type: textarea
    id: instrument-details
    attributes:
      label: Instrument details?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us how your data is structure1
      value: "Description of data hierachy"
    validations:
      required: true
  - type: textarea
    id: institution-details
    attributes:
      label: Instrument details?
      placeholder: [Node]:[Number of instruments]!
      value: "Please detail which nodes this affects, including how many instruments are affected per node"
    validations:
      required: true
